name: Build Ports Release

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so git history is available

      - name: Find last release tag
        id: lasttag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "last_tag=$tag" >> $GITHUB_ENV

      - name: Detect changed ports
        id: detect
        run: |
          mkdir -p output
          if [ -z "$last_tag" ]; then
            # First run: take all ports
            ports=$(ls -d ports/*/)
          else
            ports=$(git diff --name-only $last_tag HEAD | cut -d/ -f1-2 | sort -u | grep '^ports/')
          fi

          echo "Changed ports: $ports"
          echo "ports_list=$ports" >> $GITHUB_ENV

      - name: Zip changed ports
        if: env.ports_list != ''
        run: |
          for p in $ports_list; do
            name=$(basename "$p")
            echo "Zipping $p -> $name.zip"
            zip -r "output/${name}.zip" "$p"
          done

      - name: Create/Update Release
        if: env.ports_list != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Ports"
          files: output/*.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
