name: Build Ports Release

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  actions: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up output folder
        run: mkdir -p $GITHUB_WORKSPACE/output

      - name: Find last release tag
        id: lasttag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "Using last tag: $tag"
          echo "last_tag=$tag" >> $GITHUB_ENV

      - name: Detect changed ports
        id: detect
        run: |
          if [ -z "$GITHUB_ENV" ]; then
            echo "No env available"
          fi

          mkdir -p $GITHUB_WORKSPACE/output
          
          # Use the tag from previous step
          last_tag="${last_tag:-}"
          
          if [ -z "$last_tag" ]; then
            # First run: include all ports
            ports=$(ls -d ports/*/)
          else
            ports=$(git diff --name-only "$last_tag" HEAD | cut -d/ -f1-2 | sort -u | grep '^ports/' || true)
          fi

          echo "Changed ports: $ports"
          echo "ports_list=$ports" >> $GITHUB_ENV

      - name: Zip changed ports contents
        if: env.ports_list != ''
        run: |
          for p in $ports_list; do
            name=$(basename "$p")
            echo "Zipping contents of $p -> $name.zip"
            cd "$p"
            zip -r "$GITHUB_WORKSPACE/output/${name}.zip" ./*
            cd - >/dev/null
          done

      - name: Create or update release
        if: env.ports_list != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Ports"
          files: $GITHUB_WORKSPACE/output/*.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
